name: shellcheck-lint

on:
  push:
  pull_request:

jobs:

  test:
    runs-on: ubuntu-24.04

    steps:
     - name: checkout code
       uses: actions/checkout@v4

     - name: install shellcheck
       run: |
        sudo apt update
        sudo apt install -y shellcheck

     - name: Run shellcheck
       run: |
        shellcheck *.sh
